//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp.Entities
{
	public class ContactInfo
	{
        public string Name { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }

		public ContactInfo ()
		{
		}
	}
}

