//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace AssemblyCSharp.Entities
{
	public enum TypeName {MOODY,HAPPY, DRAMATIC, EASYGOING, SPUNKY, SLEEPY, GRUMPY, TRENDY, FUNNY, SERIOUS,FRIENDLY };

	public class FriendType
	{
		public List<TypeName> StrongAgainst{ get; set; }
		public List<TypeName> WeakAgainst{ get; set;}
		public TypeName TypeName{ get; set; }
		public int Modifier{ get; set; }

		//Base stats
		public double BaseHP{ get; set; }
		public double BaseAttack{ get; set; }
		public double BaseDefense{ get; set; }
		public double BaseSpecialAttack{ get; set; }
		public double BaseSpecialDefense{ get; set; }

		public Friend newFriend()
		{
			return new Friend (this);
		}

		public FriendType (TypeName typeName, List<FriendType> strongAgainst, List<FriendType> weakAgainst)
		{
			this.TypeName = typeName;
			this.StrongAgainst = new List<TypeName>();
			this.WeakAgainst = new List<TypeName>();
			Modifier = setModfier();
		}

		public FriendType()
		{
		}

		public int setModfier()
		{
			/*TO DO
			 * come up with formula thats type dependent
			*/
			switch(TypeName)
			{
				case TypeName.DRAMATIC:
					break;
				case TypeName.EASYGOING:
					break;
				case TypeName.FUNNY:
					break;
				case TypeName.GRUMPY:
					break;
				case TypeName.HAPPY:
					break;
				case TypeName.MOODY:
					break;
				case TypeName.SERIOUS:
					break;
				case TypeName.SLEEPY:
					break;
				case TypeName.SPUNKY:
					break;
				case TypeName.TRENDY:
					break;
			}
			//Formula to determine modifier
			return 0;
		}


		//Instatiate each type 

		/*TO DO
			*initilaize the strong and weak against lists
		*/
		//public static FriendType Moody= new FriendType(TypeName.MOODY, new List<FriendType>{},new List<FriendType> {});

		
	}

}

