//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace AssemblyCSharp.Entities
{
    public enum TrainerStyle { }
	public class Player
	{
        ContactInfo ContactInfo { get; set; }
        TrainerStyle TrainerStyle { get; set; }
        Gender Gender { get; set; }
        string NickName { get; set; }
        string Description { get; set; }
        string CatchPhrase { get; set; }
        double Experience { get; set; }
        List<Item> Inventory { get; set; }
        List<Friend> Friends { get; set; }

		public Player ()
		{
		}
	}
}

