//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp.Entities
{
	public class StatInfo
	{
        double HitPointsMax { get; set; }
        double HitPointsCurrrent { get; set; }

        double Attack{ get; set; }
        double Defence { get; set; }
        double SpecialAttack { get; set; }
        double SpecialDefence { get; set; }
        double Athletics { get; set; }
        double Intelligence { get; set; }
        double Popularity { get; set; }
        double Attractiveness { get; set; }

		public StatInfo ()
		{
		}
	}
}

